version: 2.1
orbs:
  node: circleci/node@4.0.1
workflows:
  node-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - lts
                - current
      - node/test:
          version: lts
          matrix:
            parameters:
              run-command:
                - chromatic
          requires:
            - node/test-lts
