version: 2.1
orbs:
  node: circleci/node@4.0.1
workflows:
  matchmaker:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - lts
                - current
      - node/test:
          name: chromatic
          version: lts
          run-command: chromatic
          requires:
            - node/test-lts
      - node/test:
          name: vercel
          version: lts
          run-command: vercel -- --token $VERCEL_AUTH_TOKEN
          requires:
            - node/test-lts
